-- FUTBOLCUYU BİL — live backend schema for Supabase
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, username text unique not null, total_score bigint not null default 0, total_correct integer not null default 0, total_games integer not null default 0, longest_streak integer not null default 0, answered integer not null default 0, total_time numeric not null default 0, created_at timestamptz not null default now());
create table if not exists public.game_scores(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,score integer not null check(score>=0),correct integer not null default 0,questions integer not null default 160,longest_streak integer not null default 0,duration_seconds integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.chat_messages(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id) on delete set null,username text not null,message text not null check(char_length(message) between 1 and 240),created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.game_scores enable row level security; alter table public.chat_messages enable row level security;
drop policy if exists profiles_read on public.profiles; create policy profiles_read on public.profiles for select using(true);
drop policy if exists profiles_insert_self on public.profiles; create policy profiles_insert_self on public.profiles for insert with check(auth.uid()=id);
drop policy if exists profiles_update_self on public.profiles; create policy profiles_update_self on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists scores_read on public.game_scores; create policy scores_read on public.game_scores for select using(true);
drop policy if exists scores_insert_self on public.game_scores; create policy scores_insert_self on public.game_scores for insert with check(auth.uid()=user_id);
drop policy if exists chat_read on public.chat_messages; create policy chat_read on public.chat_messages for select using(true);
drop policy if exists chat_insert_auth on public.chat_messages; create policy chat_insert_auth on public.chat_messages for insert with check(auth.uid()=user_id);
create index if not exists game_scores_score_idx on public.game_scores(score desc); create index if not exists chat_messages_created_idx on public.chat_messages(created_at desc);
create or replace view public.leaderboard as select id,username,total_score,total_correct,total_games,longest_streak from public.profiles order by total_score desc;
